language: node_js
node_js:
- '6.1'
deploy:
  app: klickr
  provider: heroku
  api_key:
    secure: eAq8Sby8X3hp92ZFEJyDyPXo38z3skoWmdQb7A7aG/FYWXtJSHQSUrVLcXBrhhAgvcvt9ATaUyVIzDpJ09trKLjCwepUzvdOakBs4vOzLVqG351YFnXmSwLcNE5jUYWpZpI5GzM0ZH8qZm4V11WnVkdPrnXYC3sCTu6HdXgvUHCeP7ysGjJQVOJB32kqQ87m4H6TKnxHa/A5BVy6ZVLpTcRa2TWWNI/Ji0aZ8EuwJh5YjpVPS5rUBVTn4yUibuAd4eyStlpvWiu42wGem2TSsfZ2z9ZZDuZwr8RbaX9yJ+fnJjihX5ivDMWmO3AatCXVfLUT6uEcJj60krWamLwmRBzShJHi3t8KV2BG43xYl6zEcP6ZdYQ6xqXHM4AtT9FkGbrTkYlN3Kz+lM1xe/ozhpLwrYaaa7eEAznF9vfWW276T79tyq1M71iGk73w8nzhfu9lcmbViUISpYlCMheHzzMy29DO8umMvo1iaX8Qar0YrZeRuPcHvW4xBExMd/FBrgB1SooAvaGlr3BVLUyaqgoFp8r/8bSiwBi2cRCok+80+gkkcZVYPe/lvvL1xesJcp+r2bL37/QIBZxNWQP4PI7d7W2deyrmlXVo+s07kJB856lcI3AwCdBuIgizB6DRkljUuS3ILNdcjFYpfmareBPXtqr+svhA4Eul/CjeiXY=
